version: '3.4'

services:
  codedelivery-simulator:
    image: projectsdocker
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
